openresty: bump to 1.13.6.2 for openssl 1.1.1 compatibility
Error:

ngx_http_encrypted_session_cipher.c:29:30: error: storage size of 'ctx' isn't known

Also see
https://github.com/openresty/encrypted-session-nginx-module/issues/12

Also outcomment SSE 4.2 patch after version bump.
Should not apply anymore today, at least we'll see
about it.