Add empty buildinfo files to windows only packages.
> [A "package tree" is constructed by looking in each directory in a root and parsing a buildinfo.json and build file from each directory.](https://github.com/dcos/dcos/blob/a7c52495843eb0e4ee57e3f3fb7b351d8c3944a0/docs/package_basics.md#package-basics)

Packagepandas valid package MUST contain a `buildinfo.json` file.
Without this file directory is not considered as a package and will not
be considered by installer resulting in following error:

```python
Building packages (4m:45s)
dcos/dcos-builder (dcos-builder) (4m:45s)
Error response from daemon: manifest for dcos/dcos-builder:dcos-builder_dockerdir-e7923dbece4519fb61876a569f5f6300cdb64eec not found
denied: requested access to the resource is denied
docker push of dcos-builder failed. This means it will be very difficult for this build to be reproduced (others will have a different / non-identical base docker for most packages.
Traceback (most recent call last):
 File "C:\BuildAgent\temp\buildTmp\dcos_build_venv\Scripts\release-script.py", line 11, in <module>
   load_entry_point('dcos-image', 'console_scripts', 'release')()
 File "c:\buildagent\work\f76365414248b6de\release\__init__.py", line 952, in main
   release_manager.create('testing', options.channel, options.tag, variants)
 File "c:\buildagent\work\f76365414248b6de\release\__init__.py", line 815, in create
   self.__config['options']['cloudformation_s3_url'] + '/' + repository_path, tree_variants)
 File "c:\buildagent\work\f76365414248b6de\release\__init__.py", line 322, in make_stable_artifacts
   all_completes = do_build_packages(cache_repository_url, tree_variants)
 File "c:\buildagent\work\f76365414248b6de\release\__init__.py", line 572, in do_build_packages
   result = pkgpanda.build.build_tree(package_store, True, tree_variants)
 File "c:\buildagent\work\f76365414248b6de\pkgpanda\build\__init__.py", line 714, in build_tree
   package_sets = [package_store.get_package_set(v) for v in tree_variants]
 File "c:\buildagent\work\f76365414248b6de\pkgpanda\build\__init__.py", line 714, in <listcomp>
   package_sets = [package_store.get_package_set(v) for v in tree_variants]
 File "c:\buildagent\work\f76365414248b6de\pkgpanda\build\__init__.py", line 372, in get_package_set
   return PackageSet(variant, TreeInfo(load_config_variant(self._packages_dir, variant, 'treeinfo.json')), self)
 File "c:\buildagent\work\f76365414248b6de\pkgpanda\build\__init__.py", line 187, in __init__
   package_store
 File "c:\buildagent\work\f76365414248b6de\pkgpanda\build\__init__.py", line 213, in package_tuples_with_dependencies
   for require in package_store.get_buildinfo(*package_tuple)['requires']:
 File "c:\buildagent\work\f76365414248b6de\pkgpanda\build\__init__.py", line 335, in get_buildinfo
   return self._packages[(name, variant)]
KeyError: ('openstackservice', None)
Process exited with code 1
```

>