Assert HTTP responses and prettify errors.
The current retrying/wait implementation waits for a condition to become
true. This is hard to debug in error cases. Even with extra logging one
has to find the correct log lines. This change introduces custom
assertion error messages for responses from HTTP requests. The error
prints the actual and expected status codes and bodies, e.g.

```
@retrying.retry(stop_max_attempt_number=3)
    def wait():
            >       assert r == Ok('hello')
            E       assert Response code from http://httpbin.org/ was 200 OK instead of 200
            E         actual body:
            E         {
            E           "origin": "127.0.0.1"
            E         }
            E         expected body:
            E         hello
```

This should ease debugging since the JUnit XML file generated by pytest
will include this message at the top.